---
title: "Greenspace Mapping"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)

```


```{r libraries}

library(tidyverse)

```


```{r LoadData}
tracts_nature <- read_csv("data/nanda_parks_tract_2018_01P.csv")
tracts_to_zip <- read_csv("data/zcta_tract_rel_10.csv")
zips_of_interest <- read_csv("data/NaturalElementsSpatialAnalysis - ZipCodes.csv")
init_data <- read_csv("data/NaturalElementsDataFinal - DatasetALLtimes.csv")
pop_data <- read_csv("data/DECENNIALPL2020.P1_data_with_overlays_2021-11-04T122132.csv")
```

```{r PopulationData}

pop_data_2020 <- pop_data[-1,] %>%
  select(GEO_ID, P1_001N) %>%
  separate(
      GEO_ID,
      into = c(NA, "GEOID"),
      sep = "US"
    ) %>%
  mutate(GEOID = as.numeric(GEOID))

```

```{r ManipulateParkData}

tracts_avg <-  
  tracts_nature %>%
  mutate(GEOID = as.numeric(tract_fips10)) %>%
  left_join(pop_data_2020) %>%
  mutate(
        parks_per_area = count_open_parks / tract_area,
        pop_per_area = as.numeric(P1_001N) / tract_area
         ) %>%
  
  select(GEOID, parks_per_area, prop_park_area_tract, pop_per_area)

```

```{r ZipData}

zip_data <-
  tracts_to_zip %>%
  
  select(ZipCode = ZCTA5, GEOID, ZAREA, ZAREAPCT) %>%
  
  left_join(tracts_avg) %>%
  
  mutate( 
          tractparks_inzip = parks_per_area * ZAREA * ZAREAPCT/100,
          tractparkarea_inzip = prop_park_area_tract * ZAREA * ZAREAPCT/100,
          tractpop_inzip = pop_per_area * ZAREA * ZAREAPCT/100
          ) %>%
  
  group_by(ZipCode) %>%
  
  summarize(
            parks_inzip = sum(tractparks_inzip, na.rm = T),
            parkarea_inzip = sum(tractparkarea_inzip, na.rm = T),
            pop_inzip = sum(tractpop_inzip, na.rm = T),
            ZAREA = ZAREA
            ) %>%
  mutate(
          prop_parkarea_inzip = parkarea_inzip / ZAREA * 100,
          pop_density_inzip = pop_inzip / ZAREA
          ) %>%
  unique()


```

```{r NationQuartile}

parks_NQ <- quantile(zip_data$parks_inzip)
parkarea_NQ <- quantile(zip_data$parkarea_inzip)
prop_parkarea_NQ <- quantile(zip_data$prop_parkarea_inzip)
pop_density_NQ <- quantile(zip_data$pop_density_inzip)

```


```{r SubjectData}

my_vars <- 
  init_data %>%
  select(prolific_ID, time, homelocation, worklocation) %>%
  
  # add if WfH (1 if subject works from homezip)
  mutate(
    WorkFrmHomeZip = case_when( 
                            homelocation == worklocation ~ 1,
                            TRUE ~ 0
                            )
  )%>%
  
  # adding home park data
  left_join(zip_data, by = c("homelocation"="ZipCode")) %>%
  select(
    prolific_ID, time, homelocation, worklocation, WorkFrmHomeZip,
    numParksHome = parks_inzip,
    areaParksHome = parkarea_inzip,
    propParksHome = prop_parkarea_inzip,
    popDensityHome = pop_density_inzip
  ) %>%
  
  # adding work park data
  left_join(zip_data, by = c("worklocation"="ZipCode")) %>%
  select(
    prolific_ID, time, homelocation, worklocation, WorkFrmHomeZip,
    numParksHome, areaParksHome, propParksHome, popDensityHome,
    
    numParksWork = parks_inzip,
    areaParksWork = parkarea_inzip,
    propParksWork = prop_parkarea_inzip,
    popDensityWork = pop_density_inzip
  ) 




```

```{r SummaryStats}
sum_stats <-
  subject_park_exposure %>%
  group_by(location) %>%
  summarize(
    avg_parks = mean(parks_inzip, na.rm = T),
    avg_parkarea = mean(parkarea_inzip, na.rm = T),
    avg_prop_parkarea = mean(prop_parkarea_inzip, na.rm = T)
  )
```

```{r plotTotalParks}
total_parks_boxplot <-
  subject_park_exposure %>%
  ggplot() +
  geom_boxplot(
    aes(
      x = location,
      y = parks_inzip,
    )) +
  labs(
    x = "Location",
    y = "Parks",
    title = "Total Parks in Respondents' Zip Codes",
  )

total_parks_boxplot
```

```{r plotParkArea}

total_parkarea_boxplot <-
  subject_park_exposure %>% 
  ggplot() +
  geom_boxplot(
    aes(
      x = location,
      y = parkarea_inzip,
    )) +
  labs(
    x = "Location",
    y = "Park Area [m^2]",
    title = "Park Area in Respondents' Zip Codes",
  )+
  ylim(0, 10000000)

total_parkarea_boxplot
```

```{r plotPropParkArea}

total_prop_parkarea_boxplot <-
  subject_park_exposure %>% 
  ggplot() +
  geom_boxplot(
    aes(
      x = location,
      y = prop_parkarea_inzip,
    )) +
  labs(
    x = "Location",
    y = "Proportion of Zip Code Area in Parks (%)",
    title = "Proportion of Park Area in Respondents' Zip Codes",
  )

total_prop_parkarea_boxplot
```
