---
title: "Mapping Participant Locations"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F, warning = F, message = F)
```

```{r libraries}

library(tidyverse)
library(tigris)
library(stringr)
library(sf)
library(leaflet)

Sys.setenv(CENSUS_KEY="dbcdeeed2f9e907f31811ee78c1f239a2aa77934")

```


```{r read data}
park_data <- read_csv("data/NaturalElementsSpatialAnalysis - TractData_OverwroteNAs.csv")

t2_tracts_all <- filter(park_data, time == 2) %>% select(prolific_ID, time, tract)

t3_tracts_all <- filter(park_data, time == 3) %>% select(prolific_ID, time, tract)

t2_tracts_park <- filter(park_data, time == 2 & !is.na(propPark)) %>% select(prolific_ID, time, tract)

t3_tracts_park <- filter(park_data, time == 3 & !is.na(propPark)) %>% select(prolific_ID, time, tract)

# us_tracts_20 <- tracts(state = NULL, cb = TRUE) %>% rename(tract = GEOID)
# write_rds(us_tracts_20, file = "data/us_tracts_20.rds")

us_tracts_20 <- read_rds( file = "data/us_tracts_20.rds")

```


```{r compile with geospatial data}


t2_tracts_mapping <- t2_tracts_all %>%
  left_join(us_tracts_20)%>% 
  st_as_sf()

t2_tracts_park_mapping <- t2_tracts_park %>%
  left_join(us_tracts_20)%>% 
  st_as_sf()


t3_tracts_mapping <- t3_tracts_all %>%
  left_join(us_tracts_20)%>% 
  st_as_sf()

t3_tracts_park_mapping <- t3_tracts_park %>%
  left_join(us_tracts_20)%>% 
  st_as_sf()

```

The tracts where survey participants lived at the time of Survey 1 are outlined in green below.     

```{r map}
tracts_of_interest <- leaflet(t2_tracts_mapping) %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolygons(
    data = t2_tracts_mapping,
    color = "green",
    opacity = 1,
    weight = 2,
    fill = F
  ) 

tracts_of_interest
```








