---
title: "Greenspace Mapping"
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r libraries}
library(tidyverse)
```

```{r LoadData}
tracts_nature <- read_csv("data/nanda_parks_tract_2018_01P.csv")
tracts_to_zip <- read_csv("data/zcta_tract_rel_10.csv")
zips_of_interest <- read_csv("data/NaturalElementsSpatialAnalysis - ZipCodes.csv") %>%
  select(Prolific_ID, Frst_HomeZip = D_Home_Location, Scnd_HomeZip = "2D_Home_Location", 
         Frst_WorkZip = D_Work_Location, Scnd_WorkZip = "2D_Work_Location")
```

```{r ManipulateParkData}
tracts_nature_avg <-  
  tracts_nature %>%
  mutate(parks_per_area = count_open_parks / tract_area,
         GEOID = as.numeric(tract_fips10)
         ) %>%
  select(GEOID, parks_per_area, prop_park_area_tract)
```

```{r ZipParks}
zip_parks <-
  tracts_to_zip %>%
  
  select(ZipCode = ZCTA5, GEOID, ZAREA, ZAREAPCT) %>%
  
  left_join(tracts_nature_avg) %>%
  
  mutate( 
          tractparks_inzip = parks_per_area * ZAREA * ZAREAPCT/100,
          tractparkarea_inzip = prop_park_area_tract * ZAREA * ZAREAPCT/100
          ) %>%
  
  group_by(ZipCode) %>%
  
  summarize(
            parks_inzip = sum(tractparks_inzip, na.rm = T),
            parkarea_inzip = sum(tractparkarea_inzip, na.rm = T),
            ZAREA = ZAREA
            ) %>%
  mutate(
          prop_parkarea_inzip = parkarea_inzip / ZAREA * 100
          )
```

```{r SubjectsPark}
subject_park_exposure <- 
  zips_of_interest %>%
  pivot_longer(
    cols = c("Frst_HomeZip", "Frst_WorkZip", "Scnd_HomeZip", "Scnd_WorkZip"),
    names_to = "location",
    values_to = "ZipCode"
  ) %>%
  
  left_join(zip_parks) %>% 
  
  group_by(location) %>%
  
  unique()
```


```{r SummaryStats}
sum_stats <-
  subject_park_exposure %>%
  group_by(location) %>%
  summarize(
    avg_parks = mean(parks_inzip, na.rm = T),
    avg_parkarea = mean(parkarea_inzip, na.rm = T),
    avg_prop_parkarea = mean(prop_parkarea_inzip, na.rm = T))
```

```{r plotTotalParks}
total_parks_boxplot <-
  subject_park_exposure %>%
  ggplot() +
  geom_boxplot(
    aes(
      x = location,
      y = parks_inzip,
    )) +
  labs(
    x = "Location",
    y = "Parks",
    title = "Total Parks in Respondents' Zip Codes \n",
  )
total_parks_boxplot
```

```{r plotParkArea}
total_parkarea_boxplot <-
  subject_park_exposure %>% 
  ggplot() +
  geom_boxplot(
    aes(
      x = location,
      y = parkarea_inzip,
    )) +
  labs(
    x = "Location",
    y = "Park Area [m^2]",
    title = "Park Area in Respondents' Zip Codes \n",
  )+
  ylim(0, 10000000)
total_parkarea_boxplot
```

```{r plotPropParkArea}
total_prop_parkarea_boxplot <-
  subject_park_exposure %>% 
  ggplot() +
  geom_boxplot(
    aes(
      x = location,
      y = prop_parkarea_inzip,
    )) +
  labs(
    x = "Location",
    y = "Proportion of Zip Code Area in Parks (%)",
    title = "Proportion of Park Area in Respondents' Zip Codes  \n",
  )
total_prop_parkarea_boxplot
```

```{r filterWfH}
subject_park_exposure_noWfH <- 
  zips_of_interest %>%
  filter( !(`Scnd_HomeZip` == `Scnd_WorkZip`)
    
  )%>%

  pivot_longer(
    cols = c("Frst_HomeZip", "Frst_WorkZip", "Scnd_HomeZip", "Scnd_WorkZip"),
    names_to = "location",
    values_to = "ZipCode"
  ) %>%
  
  left_join(zip_parks) %>% 
  
  group_by(location) %>%
  
  unique()


```


```{r plotTotalParks}
total_parks_boxplot_noWfH <-
  subject_park_exposure_noWfH %>%
  ggplot() +
  geom_boxplot(
    aes(
      x = location,
      y = parks_inzip,
    )) +
  labs(
    x = "Location",
    y = "Parks",
    title = "Total Parks in Respondents' Zip Codes \n (Exclude Work From Home on Second Survey)",
  )

total_parks_boxplot_noWfH
```

```{r plotParkArea}
total_parkarea_boxplot_noWfH <-
  subject_park_exposure_noWfH %>% 
  ggplot() +
  geom_boxplot(
    aes(
      x = location,
      y = parkarea_inzip,
    )) +
  labs(
    x = "Location",
    y = "Park Area [m^2]",
    title = "Park Area in Respondents' Zip Codes \n (Exclude Work From Home on Second Survey)",
  )+
  ylim(0, 10000000)
total_parkarea_boxplot_noWfH
```

```{r plotPropParkArea}
total_prop_parkarea_boxplot_noWfH <-
  subject_park_exposure_noWfH %>% 
  ggplot() +
  geom_boxplot(
    aes(
      x = location,
      y = prop_parkarea_inzip,
    )) +
  labs(
    x = "Location",
    y = "Proportion of Zip Code Area in Parks (%)",
    title = "Proportion of Park Area in Respondents' Zip Codes \n (Exclude Work From Home on Second Survey)",
  )
total_prop_parkarea_boxplot_noWfH
```


